"""Backend interfaces (§5). Kept deliberately narrow so implementations can
swap freely (pynput vs raw SendInput, real vs fake in tests)."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


class AudioBackend(Protocol):
    def get_volume(self) -> float: ...
    def set_volume(self, level: float) -> None: ...
    def step_volume(self, delta: float) -> None: ...
    def mute_toggle(self) -> None: ...


class InputBackend(Protocol):
    def tap_chord(self, chord: str) -> None: ...
    def tap_vk(self, vk: int) -> None: ...
    def scan_key_down(self, vk: int) -> None: ...
    def scan_key_up(self, vk: int) -> None: ...
    def scan_tap(self, vk: int, with_shift: bool = False) -> None: ...
    def scroll(self, delta: int) -> None: ...


class WindowBackend(Protocol):
    def switcher_begin(self) -> None: ...
    def switcher_step(self, forward: bool) -> None: ...
    def switcher_end(self) -> None: ...
    def desktop_switch(self, direction: str) -> None: ...
    # Direct targeting (tier 2).
    def list_windows(self) -> list[int]: ...
    def get_foreground(self) -> int: ...
    def window_title(self, hwnd: int) -> str: ...
    def focus_window(self, hwnd: int) -> None: ...


class MediaBackend(Protocol):
    def play_pause(self) -> None: ...
    def next_track(self) -> None: ...
    def prev_track(self) -> None: ...


class CustomBackend(Protocol):
    def run_shell(self, cmd: str) -> None: ...
    def launch(self, target: str) -> None: ...


@dataclass
class Backends:
    """The bundle handed to actions; owned by the dispatcher thread."""

    audio: AudioBackend
    input: InputBackend
    window: WindowBackend
    media: MediaBackend
    custom: CustomBackend
